<?php

namespace AppBundle\Repository;

/**
 * OrderDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
