app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_logout:
    path: "/odhlasit"
    
api:
    resource: "@AppBundle/Controller/ApiController.php"
    type:     rest
    prefix:   /api
